### ISSUE TITLE
Unable to remove 'focus' style from checkbox

### ISSUE THREAD

**Issue by AustinShelby** [tailwindlabs/tailwindcss-forms#10]
Here is an example that shows what's happening: https://play.tailwindcss.com/bz1AKpJywn

I was unable to remove a very subtle white outline (seems to be a `box-shadow`) from a checkbox even when using classes `border-none focus:ring-0 focus:shadow-none`.

I only managed to remove it by adding ` style="box-shadow: none"` to the input.

|Browser|Version|
|---|---|
|Chromium|Version 87.0.4280.66 (Official Build) snap (64-bit)|

**Comment by AustinShelby** [comment]
Ok dumb mistake I forgot to add `ring-offset-0`

**Comment by CharlesOuverleaux** [comment]
> Ok dumb mistake I forgot to add `ring-offset-0`

God thank you! Found this only after hours of trying to remove this!
