### ISSUE TITLE
Is 0.4.0 released or not?

### ISSUE THREAD

**Issue by memark** [tailwindlabs/tailwindcss-forms#101]
### What version of @tailwindcss/forms are you using?

0.4.0

### What version of Node.js are you using?

n/a

### What browser are you using?

n/a

### What operating system are you using?

n/a

### Reproduction repository

n/a

### Describe your issue

0.4.0 is listed as alpha on [Releases page](https://github.com/tailwindlabs/tailwindcss-forms/releases), yet it shows up on npm with "latest" tag. (There is also a "next" tag, but noone is downloading that.) `npm install @tailwindcss/forms` gives everyone 0.4.0, even without any tags. Is it an alpha or not? Is it stable?

From https://www.npmjs.com/package/@tailwindcss/forms
<img width="754" alt="image" src="https://user-images.githubusercontent.com/318504/151669860-994de220-ddc5-4c29-ab89-43a4292072f2.png">

**Comment by adamwathan** [comment]
It's released and not alpha. NPM is source of truth for versions 👍🏻

**Comment by memark** [comment]
OK, thank you, then I know.

You _might_ still want to address the fact that the GitHub page is then misleading:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/318504/151831850-25e9970d-836b-4901-be28-142757022b59.png">
