### ISSUE TITLE
Checkbox display issue with CSP enabled

### ISSUE THREAD

**Issue by vhscom** [tailwindlabs/tailwindcss-forms#102]
### What version of @tailwindcss/forms are you using?

v0.4.0

### What version of Node.js are you using?

v17.3.0

### What browser are you using?

Ungoogled Chromium

### What operating system are you using?

Arch Linux

### Reproduction repository

https://codeberg.org/vhs/repro-tailwind-forms-checkbox-issue

### Describe your issue

Dependent on CSP settings checkboxes do not display correctly due to [use of `data` scheme](https://security.stackexchange.com/questions/94993/is-including-the-data-scheme-in-your-content-security-policy-safe).

Here's what the checkbox looks like with strict CSP enabled:

![repro](https://user-images.githubusercontent.com/97140109/153135203-8c53a836-c6c5-4a58-bb32-c507734efa27.png)

Issue occurs because `tailwindcss-forms` checkbox uses a base64-encoded SVG background image. To validate this is the case simply build the repro with `pnpm i && pnpm dev -- --open` then open `svelte.config.js` and remove the CSP setting (browser will auto-reload showing the checkbox).

Is it possible to add a fallback experience for apps blocking unsafe evaluation of `data` attributes?

**Comment by vhscom** [comment]
I found a reasonable workaround for the display issue which is to save the SVG graphic to a file and add a style rule to use the _image_ as the background as opposed to attempting to inline a `data` uri (allowed under strict CSP). And while this does not address the CSP error being thrown by the browser at runtime it at least addresses the cosmetic part of this issue.

I'm still looking for a clean way to eliminate the CSP error the browser throws regarding the forms css as it seems there's no clean way to do that unless I scrape the generated styles on the server and delete, or rebuild this library.

**Comment by vhscom** [comment]
I found a reasonable workaround for the display issue which is to save the SVG graphic to a file and add a style rule to use the _image_ as the background (allowed under strict CSP) as opposed to attempting to inline a `data` uri . And while this does not address the CSP error being thrown by the browser at runtime as a result of the data uri it at least addresses the cosmetic part of this issue.

I'm still looking for a clean way to eliminate the CSP error the browser throws regarding the forms css as it seems there's no clean way to do that unless I scrape the generated styles on the server and delete, or rebuild this library. I'm open to suggestions, though I feel this use case is not common enough to warrant being addressed further within the library so I'm going to close this ticket and handle the resolution in userland. :smile:

**Comment by theonelucas** [comment]
> I found a reasonable workaround for the display issue which is to save the SVG graphic to a file and add a style rule to use the _image_ as the background (allowed under strict CSP) as opposed to attempting to inline a `data` uri . Doing so causes the browser to skip attempting to use `data:`.

The SVG file:

```svg
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='white'><path d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z' /></svg>
```

The rule:
```css
.form-checkbox:checked {
    background-image: url("/site/assets/icons/checkbox.svg");
}
```
