### ISSUE TITLE
Radio button groups not marked up correctly

### ISSUE THREAD

**Issue by MelSumner** [tailwindlabs/tailwindcss-forms#108]
### What version of @tailwindcss/forms are you using?

v0.4.0

### What version of Node.js are you using?

16

### What browser are you using?

n/a

### What operating system are you using?

macOS

### Reproduction repository

https://codepen.io/melsumner/pen/podxbyq

### Describe your issue

The radio buttons do not have the correct markup. I have provided a codepen that demonstrates the correct markup.

**Comment by adamwathan** [comment]
Hey! Sorry do you mind clarifying what you are looking to fix here? The library just provides CSS and no markup so there's nothing to correct in the library itself.

Is it just the little internal demo on the kitchen sink page here we use to visually double check the styles in development?

https://tailwindcss-forms.vercel.app/kitchen-sink.html

Happy to update but the Codepen you shared has completely different content so want to make sure I'm understanding.

If so one thing I would love to know is if the separate label + input elements using `for` is actually necessary or if wrapping the input with the label is ok? I've always understood that to be valid and accessible, so if the only thing that needs to be changed is the fieldset stuff we can just make that change.

**Comment by adamwathan** [comment]
Updated the kitchen sink page markup here: https://github.com/tailwindlabs/tailwindcss-forms/commit/1bd06b1ea5c38aa5e16e9a7b234d3cf69a79cb1f

I'm still not sure I've understood the original issue correctly so if I've misunderstood please feel free to open another one or even better just a PR with whatever improvements you think are needed, thanks.
