### ISSUE TITLE
[FR] Optional class for piecemeal migration from other frameworks

### ISSUE THREAD

**Issue by chasegiunta** [tailwindlabs/tailwindcss-forms#11]
Upon trying to migrate an app/site over to Tailwind, we may want to utilize tailwindcss-forms (since it seems like the path forward), but this is currently an all-or-nothing approach. The Bootstrap app I'm currently migrating is so vast that I'm not sure about everywhere that form fields are even being used.

I'm wondering if it's possible to configure something to use similar to tailwind-custom-forms where we can opt into a class required on form elements where we want tailwindcss-forms to take over.

**Comment by ulken** [comment]
I would prefer a (parent) selector strategy similar to how [!important](https://tailwindcss.com/docs/configuration#selector-strategy) works. That way resets/custom styles would only be applied to descendants of the selector.

**Comment by daniel-zahariev** [comment]
I think the best approach here would be to add the styles as utility classes instead of adding them to base.

**Comment by adamwathan** [comment]
Added a new class strategy in v0.3.0 that should handle this, thanks to @chasegiunta 👍
