### ISSUE TITLE
Purged attribute selectors

### ISSUE THREAD

**Issue by ayrton** [tailwindlabs/tailwindcss-forms#12]
Looks like PurgeCSS automatically purges the attribute selectors eg `[type='checkbox']`. 

I had to add the following rule to the safelist:

```js
module.exports = {
  plugins: [require("@tailwindcss/forms")],
  purge: {
    options: {
      safelist: [
        "type", // [type='checkbox']
      ],
    },
    preserveHtmlElements: true,
  },
};
```

Should this be something that is set up out of the box? I'm happy to PR if you can point me into the right direction

**Comment by YashVadhadiya** [comment]
Try this.

`<html>
  <body>
    <div class="component"></div>
  </body>
</html>`

following CSS

`.component { color: black; }
button,
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}`

Passing the above HTML and CSS through the CLI
The resulting CSS is as followed

`.component { color: black; }
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}`

The generated CSS should be

`.component { color: black; }`

I found this [here](https://github.com/FullHuman/purgecss/issues/110)

> Looks like PurgeCSS automatically purges the attribute selectors eg `[type='checkbox']`.
> 
> I had to add the following rule to the safelist:
> 
> ```js
> module.exports = {
>   plugins: [require("@tailwindcss/forms")],
>   purge: {
>     options: {
>       safelist: [
>         "type", // [type='checkbox']
>       ],
>     },
>     preserveHtmlElements: true,
>   },
> };
> ```
> 
> Should this be something that is set up out of the box? I'm happy to PR if you can point me into the right direction

**Comment by fulljames** [comment]
I was experiencing this on a `[type=password]` while compiling CSS for a Shopify theme - turned out the `content` rules weren't looking correctly into sub-folders so it was skipping the file.

**Comment by alexbu92** [comment]
@fulljames  how did you solve this?

**Comment by fulljames** [comment]
> @fulljames how did you solve this?

I tweaked the `content` section of the `purge` settings tailwind.config.js, e.g. changing `'./templates/*.liquid'` to `'./templates/**/*.liquid'` to look into sub-directories.

```
  purge: {
    enabled: true,
    content: [
      './layout/*.liquid',
      './templates/**/*.liquid',
      './sections/*.liquid',
      './snippets/*.liquid',
    ],
  },
```

**Comment by dzajic** [comment]
> > @fulljames how did you solve this?
> 
> I tweaked the `content` section of the `purge` settings tailwind.config.js, e.g. changing `'./templates/*.liquid'` to `'./templates/**/*.liquid'` to look into sub-directories.
> 
> ```
>   purge: {
>     enabled: true,
>     content: [
>       './layout/*.liquid',
>       './templates/**/*.liquid',
>       './sections/*.liquid',
>       './snippets/*.liquid',
>     ],
>   },
> ```

@fulljames We're already doing this and are still experiencing the issue with a password field not getting the same styles applied as other input types. 😕

**Comment by ayrton** [comment]
> > > @fulljames how did you solve this?
> 
> > 
> 
> > I tweaked the `content` section of the `purge` settings tailwind.config.js, e.g. changing `'./templates/*.liquid'` to `'./templates/**/*.liquid'` to look into sub-directories.
> 
> > 
> 
> > ```
> 
> >   purge: {
> 
> >     enabled: true,
> 
> >     content: [
> 
> >       './layout/*.liquid',
> 
> >       './templates/**/*.liquid',
> 
> >       './sections/*.liquid',
> 
> >       './snippets/*.liquid',
> 
> >     ],
> 
> >   },
> 
> > ```
> 
> 
> 
> @fulljames We're already doing this and are still experiencing the issue with a password field not getting the same styles applied as other input types. 😕

Did you try adding `"type"` to the allowlist? (See snippet of the description above)

**Comment by dzajic** [comment]
We've decided to go and update all our dependencies first (a bit of a nightmare). Once we achieve that, we'll see where we stand (it could be a while), but we'll try the `allowlist` if we need to.
For now, this isn't a major problem as it only affects one infrequently used form in our back office web app.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Make sure that you provide all the paths to your files/content in `purge: []` or `purge: { content: [] }`, otherwise purge will indeed purge these styles.
https://tailwindcss.com/docs/optimizing-for-production#removing-unused-css
