### ISSUE TITLE
No longer works with @nuxtjs/tailwindcss - 5.1.2

### ISSUE THREAD

**Issue by DenysPoliarush** [tailwindlabs/tailwindcss-forms#123]
### What version of @tailwindcss/forms are you using?

0.5.0

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

-

### Describe your issue

It stopped working after the update @nuxtjs/tailwindcss to version 5.1.2. It does not produce any errors, it just has no styles.

**Comment by thecrypticace** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
