### ISSUE TITLE
Tailwindcss/forms failed to install

### ISSUE THREAD

**Issue by Dynalogical** [tailwindlabs/tailwindcss-forms#125]
### What version of @tailwindcss/forms are you using?

Latest

### What version of Node.js are you using?

V15.5.1

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### Reproduction repository

-

### Describe your issue

I don't have any reproduction repo but I think I just found a bug. I'm using Tailwind V2.

npm install -D @tailwindcss/forms@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@2.2.19
npm ERR! node_modules/tailwindcss
npm ERR!   tailwindcss@"^2.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@">=3.0.0 || >= 3.0.0-alpha.1" from @tailwindcss/forms@0.5.2
npm ERR! node_modules/@tailwindcss/forms
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/stef/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stef/.npm/_logs/2022-08-07T21_20_43_806Z-debug.log

**Comment by thecrypticace** [comment]
Since you're using Tailwind CSS v2 you'll want to install using `npm install -D @tailwindcss/forms@0.3` as the latest version is for Tailwind CSS v3.0+

Hope that helps!

**Comment by Dynalogical** [comment]
Yes, that totally worked! Thank you 😃
