### ISSUE TITLE
missing checkbox styling on safari

### ISSUE THREAD

**Issue by dsazup** [tailwindlabs/tailwindcss-forms#13]
Hello, I am seeing a strange bug with checkboxes on safari. It doesn't apply styling when I am using this as a plugin.

E.g on safari I see this:
![Screenshot 2020-11-21 at 17 58 06](https://user-images.githubusercontent.com/8631224/99884069-31728b80-2c23-11eb-9b2b-3e8b01df05bd.png)

I added it as a plugin to tailwind.config.js, as you can see it applies styling correctly to the inputs (except checkbox). Now comes the strange part, if I add 
```
  <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/forms@0.2.1/dist/forms.min.css" />
```
after my app.css, it works 😄 

![Screenshot 2020-11-21 at 18 00 11](https://user-images.githubusercontent.com/8631224/99884095-67b00b00-2c23-11eb-8b5f-9a6a2130a1b8.png)

So wondering if I am missing something here. Running pretty much default everything. Only have 
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
in my app.css 🤔  

and tailwind.config.js is default
```
module.exports = {
  purge: [],
  theme: {
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```
package versions
```
 "tailwindcss": "^2.0.1",
 "@tailwindcss/forms": "^0.2.1",
```

any ideas what I could be missing, or is this a bug? Let me know if there is any other information I can supply, thanks.

**Comment by adamwathan** [comment]
Hey! Do you have autoprefixer configured properly in your PostCSS configuration?

**Comment by dsazup** [comment]
Ahh, that was it! It was running before tailwind, totally missed it. 🤦  Thank you very much, it all works perfectly now 👌
