### ISSUE TITLE
Can you set the default value for a "date" input? 

### ISSUE THREAD

**Issue by robbieallen** [tailwindlabs/tailwindcss-forms#15]
It doesn't seem to use the value attribute and defaults to "mm/dd/yyyy" no matter what.

**Comment by iksaku** [comment]
This plugin doesn't provide any default value nor value modification for your inputs. Only styling is done.

In order to set a default value to your input element, please refer to [MDN's documentation on date inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value).

**Comment by robbieallen** [comment]
I see now. It wanted the value attribute in the format of YYYY-mm-dd.
