### ISSUE TITLE
'require' not define, cannot import plugin to tailwind config

### ISSUE THREAD

**Issue by vim-diesel** [tailwindlabs/tailwindcss-forms#151]
### What version of @tailwindcss/forms are you using?

10.2.3

### What version of Node.js are you using?

v20.9.0

### What browser are you using?

Edge

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/vim-diesel/vite-eslint

### Describe your issue

Attempting to import the plugin to tailwind.config.js throws an error:

![image](https://github.com/tailwindlabs/tailwindcss-forms/assets/37084860/435eb125-3a5e-415b-ab00-22069925357a)

**Comment by vim-diesel** [comment]
I may have found a fix, although I'm not sure if it is a fix or a bandaid:

To specify environments in a configuration file, use the env key and specify which environments you want to enable by setting each to true. For example, the following enables the browser, es6 and Node.js environments:

In your .eslintrc.js file ;
```
env: {
   browser: true,
   node: true,    <<<<--- Add this
   es6: true
 },
```

**Comment by thecrypticace** [comment]
Hey, this is a project configuration thing — especially given that these errors are coming from ESLint.

However, if you're in a Vite project I'd suggest using `import` instead of `require` anyway as this is the proper way to do this when using ES Modules:

```js
import formsPlugin from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [formsPlugin],
}
```

**Comment by shivangi-2001** [comment]
Remove this plugin install in vscode
![image](https://github.com/tailwindlabs/tailwindcss-forms/assets/102828355/5d239546-f9a1-4b52-8301-242ed8c7f05a)

**Comment by Pizle0210** [comment]
##solution##
This worked for me.

change from module to common js in tailwind.config

![Screenshot From 2024-11-08 16-03-41](https://github.com/user-attachments/assets/562aa03e-39e8-4c72-b745-6afb7de7c483)

**Comment by yamanidev** [comment]
@Pizle0210  did you change the file from `tailwind.config.ts` to `tailwind.config.cjs`?

**Comment by iyouushh** [comment]
import plugin from "tailwindcss-animate"; <= import 

/
..code ...
/
  plugins: [plugin],
