### ISSUE TITLE
No color on select chevron when overriding colors in config

### ISSUE THREAD

**Issue by tomvo** [tailwindlabs/tailwindcss-forms#165]
### What version of @tailwindcss/forms are you using?

0.5.8

### What version of Node.js are you using?

v20.14.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/IfznFpbjNy?file=config

### Describe your issue

It seems strange this is happening but overriding colors in theme config removes the color for the select chevron. You can see the variable is not replaced in the SVG image of the chevron.

**Comment by tomvo** [comment]
It seems actually specifically to happen when overriding the gray-500 class. See here for a specific case: https://play.tailwindcss.com/1TWXFAuYbt?file=config

**Comment by tomvo** [comment]
Thanks for this Adam!

**Comment by adamwathan** [comment]
If you update to v0.5.9 you should at least see a chevron now!
