### ISSUE TITLE
Allow ring color change via class on checkbox

### ISSUE THREAD

**Issue by welcoMattic** [tailwindlabs/tailwindcss-forms#19]
I'm trying to change the color of a checkbox, it works for the checkbox itself, but not for the outline of the checkbox.

```html
<input type="checkbox" class="rounded text-indigo-500 ring-indigo-300">
```

![image](https://user-images.githubusercontent.com/773875/100643608-953f3780-333a-11eb-840e-e2320f80b106.png)

Is there any way to force this? Or is it a bug?

**Comment by shornuk** [comment]
Presumably you only want the ring on focus? If so, this should do it (and works for me)...
```html
<input type="checkbox" class="rounded text-indigo-500 focus:ring-indigo-300">
```
https://play.tailwindcss.com/TvjY5NyGgv

**Comment by welcoMattic** [comment]
You are right! Sorry for that :see_no_evil:
