### ISSUE TITLE
Can you bring back `form-input`, `form-select`, etc?

### ISSUE THREAD

**Issue by jeffsawatzky** [tailwindlabs/tailwindcss-forms#20]
Hello, I use emberjs, along with the ember-power-select addon for custom select boxes. Ember-power-select uses a `div` for the select trigger and not a `select` element. Previously I was able to style it with tailwind-custom-forms using a `form-select` class, but now I can't.

Its great that we don't need to add these classes to normal form elements, but sometimes we need to style a non-form element as one, and these classes made it easy.

**Comment by zeppelin** [comment]
When transitioning from an existing CSS framework to Tailwind, it'd be great if elements were not targeted directly - or at least an option existed to specify classnames to avoid clashes. That would solve the above use-case, and also avoid vendor lock-in to this plugin.

**Comment by chasegiunta** [comment]
Related to #11

**Comment by adamwathan** [comment]
Added a new class strategy in v0.3.0 that should handle this, thanks to @chasegiunta 👍
