### ISSUE TITLE
Migrating from @tailwindcss/custom-forms to @tailwindcss/forms causes error in Gatsby build

### ISSUE THREAD

**Issue by alexdkaminski** [tailwindlabs/tailwindcss-forms#26]
I have upgraded to Tailwind 2.0 which builds successfully in Gatsby but as soon as I replace @tailwindcss/custom-forms with @tailwindcss/forms I get the following build error:

```javascript
success write out requires - 0.129s
success run static queries - 0.316s - 8/8 25.30/s
success run page queries - 0.209s - 44/44 210.51/s
success Generating image thumbnails - 12.735s - 52/52 4.08/s
error undefined failed

Cannot read property 'none' of undefined
error undefined failed

Cannot read property 'none' of undefined
error undefined failed

Cannot read property 'none' of undefined
failed Building development bundle - 16.430s
```

I've run `npm install tailwindcss@latest postcss@latest autoprefixer@latest`

Any help would be greatly appreciated.

**Comment by KhaledSMQ** [comment]
@alexdkaminski what was the problem ? i am facing the same issue

**Comment by alexdkaminski** [comment]
I updated gatsby-plugin-sharp to 2.6.26 and gatsby-transformer-sharp to ^2.5.15.
