### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by joaopaulobdac** [tailwindlabs/tailwindcss-forms#29]
I would love to have a consistent default appearance of buttons across browsers and operating systems to build upon and not have to worry about testing to see if I missed some style.

**Comment by joaopaulobdac** [comment]
Honestly, on second thought, I think the appearance given by Preflight is good enough. When I opened this issue it was my first time using tailwind and I didn't realize that Preflight also cleaned the default button appearance. I'll leave this issue open in case the maintainers want some discussion to happen, but I think it's ok to close it.

**Comment by adamwathan** [comment]
Yeah in the spirit of what this plugin does I think it's probably best not to touch buttons, we are just trying to make things styleable and buttons are already reset enough to be utility-friendly out of the box 👍🏻
