### ISSUE TITLE
Cannot disable radio outlines

### ISSUE THREAD

**Issue by jaredgalanis** [tailwindlabs/tailwindcss-forms#32]
When using this package it seems to cause any classes like `focus:outline-none` or project wide configuration for outlines such as:
```
  corePlugins: {
    outline: false,
  }
```
to be ignored.

**Comment by adamwathan** [comment]
Outlines are already disabled for all form elements using this package. The outline you see come from the "ring" utilities. You can use "focus:ring-0" to remove it for example.

**Comment by adamwathan** [comment]
If I'm misunderstanding please provide an actual reproduction that shows the problem and I can look into it.

**Comment by jaredgalanis** [comment]
Thanks, @adamwathan! That definitely got rid of the exterior ring. 

Not necessarily the same thing, but do you have any sense of what this interior outline is and how to remove it?

![Screen Shot 2020-12-30 at 7 04 46 AM](https://user-images.githubusercontent.com/6305935/103350364-b7c58d00-4a6d-11eb-9a11-def41016813b.png)


`<input type="radio" class="h-8 w-8 cursor-pointer text-red-500 focus:ring-0">`

**Comment by jaredgalanis** [comment]
> Thanks, @adamwathan! That definitely got rid of the exterior ring.
> 
> Not necessarily the same thing, but do you have any sense of what this interior outline is and how to remove it?
> 
> ![Screen Shot 2020-12-30 at 7 04 46 AM](https://user-images.githubusercontent.com/6305935/103350364-b7c58d00-4a6d-11eb-9a11-def41016813b.png)
> 
> `<input type="radio" class="h-8 w-8 cursor-pointer text-red-500 focus:ring-0">`

Looks like maybe it is coming from the way outline-none is handled. If I apply a custom css selector with `outline: none;` that inner blue outline goes away.
