### ISSUE TITLE
<input> decimal for price

### ISSUE THREAD

**Issue by enri90** [tailwindlabs/tailwindcss-forms#34]
hello everyone 
how do i use <input> number in decimal to specify the price of a product?

thx

**Comment by ordago** [comment]
@enri90 you use the attribute `step`

```html
<input type="number" name="price" step="0.01">
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You can do that with the information @ordago provided.
