### ISSUE TITLE
Vite Vue3 app breaks when @tailwindcss/forms is added as an npm dependency

### ISSUE THREAD

**Issue by jim0thy** [tailwindlabs/tailwindcss-forms#35]
Creating a brand new Vue3 app with the Tailwind 2.0 compatibility build, then adding `@tailwindcss/forms` causes the error shown below in the app build.

```
Dep optimization failed with error:
(node:17868) UnhandledPromiseRejectionWarning: Error: 'promisify' is not exported 
by __browser-external, imported by node_modules/purgecss/lib/purgecss.esm.js
```

The error occurs as soon as `@tailwindcss/forms` is added to `node_modules`, regardless of it being required as plugin in `tailwind.config.js`. Removing the dependency with npm fixes the build.

Is there a compatibility build of `@tailwindcss/forms` that I need to use with Vite, or do I need to wait for Vite to update to PostCSS 8?

There's an example repo here that replicates the problem:
https://github.com/jim0thy/tailwindcss-forms-vite-test

My set-up is:
**OS**: MacOS 11.1
**Node**: v14.15.4
**npm**: v6.14.10

**Comment by jim0thy** [comment]
Moving `@tailwindcss/forms` to `devDependencies` solves the problem.

Leaving the issue open in case you want to make a note in the readme about it.

**Comment by lewebsimple** [comment]
I'm having a different issue with Vite 2.0.0-beta.47 when using the following inside tailwind.config.js:
```
plugins: [require("@tailwindcss/forms")],
```
The error is :
```
[vite] Internal server error: Cannot find module 'tailwindcss/plugin'
```
This is probably due to the way Vite imports things...

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This looks like an issue with another dependency. Glad your problem is solved!
