### ISSUE TITLE
Built-in icons (data: xml+svg) prevents usage of strict Content Security Policy. How to disable it?

### ISSUE THREAD

**Issue by goenning** [tailwindlabs/tailwindcss-forms#42]
It's currently not possible to use tailwindcss-forms on a strict policy without adding a `style-src: data:` which, as stated by MDN, [is insecure and not recommended.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src)

I there a way to disable/remove/override built-in icons? I tried a custom theme config, but it didn't work (I'm probably doing it wrong).

```js
customForms: (theme) => ({
  default: {
    select: {
      backgroundImage: 'none',
    },
  },
}),
```

The violation is triggered here:

https://github.com/tailwindlabs/tailwindcss-forms/blob/98f761963928dc59ea71e9f4804c2544f1a2ce6f/src/index.js#L67-L73

**Comment by adamwathan** [comment]
Hey! If you'd like to override any of the styles you need to do so in CSS, so something like:

```css
[type="checkbox"]:checked {
  backgorund-image: none
}
```

...and similar 👍 No plans to remove these by default unfortunately, this is the only real approach to adding icons to elements like this and is pretty standard (Bootstrap does it as well for example). I don't see how this is a security issue in this CSS in particular, although I understand how allowing data URIs to come from end users could be a problem.

**Comment by goenning** [comment]
Wow, such a simple solution that I should have tried that before posting this 🤦 Thanks for that! hopefully it'll be useful for others too.

I really thought it would trigger a violation regardless, but it doesn't, the override prevents the browser from even trying to load the icon  :+1:
