### ISSUE TITLE
How do you configure this plugin to work with purge?

### ISSUE THREAD

**Issue by leesmith** [tailwindlabs/tailwindcss-forms#43]
Rails 6.1, Tailwindcss 2.0.3

The CSS resets that this plugin provides are getting clobbered by my purge settings in `tailwind.config.js`:

```
module.exports = {
  purge: [
    './app/**/*.html.erb',
    './app/**/*.html.haml',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

`package.json`

```
{
  "name": "bham_food_scores_api",
  "private": true,
  "dependencies": {
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "^5.2.1",
    "@tailwindcss/forms": "^0.2.1",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.2"
  }
}

```

What am I doing wrong with this config? Many thanks!

**Comment by iv-mexx** [comment]
Yeah I'm having the same problem right now. I tried adding `type` to the `purge savelist (https://github.com/tailwindlabs/tailwindcss-forms/issues/12) but thats not working for me...

**Comment by dnsbty** [comment]
I'm seeing the same issue (with Phoenix as my backend rather than Rails) and 

package.json
```json
{
  "repository": {},
  "description": " ",
  "license": "MIT",
  "scripts": {
    "deploy": "NODE_ENV=production webpack --mode production",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "phoenix_live_view": "file:../deps/phoenix_live_view"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@tailwindcss/forms": "^0.2.1",
    "alpinejs": "^2.8.0",
    "autoprefixer": "^10.2.4",
    "babel-loader": "^8.0.0",
    "copy-webpack-plugin": "^5.1.1",
    "css-loader": "^3.4.2",
    "hard-source-webpack-plugin": "^0.13.1",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss": "^8.2.4",
    "postcss-import": "^14.0.0",
    "postcss-loader": "4.2",
    "prettier": "^2.2.1",
    "prettier-plugin-eex": "^0.1.0",
    "sass-loader": "^8.0.2",
    "tailwindcss": "^2.0.2",
    "terser-webpack-plugin": "^2.3.2",
    "webpack": "4.41.5",
    "webpack-cli": "^3.3.2"
  }
}
```

tailwind.config.js
```js
module.exports = {
  purge: ["../lib/**/*.ex", "../lib/**/*.leex", "../lib/**/*.eex", "./js/**/*.js"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
};
```

I grep my production CSS for `datetime-local` and it returns nothing, but if I comment out the `purge` line from my `tailwind.config.js` and build again, grepping for `datetime-local` shows the reset.

**Comment by leesmith** [comment]
@dnsbty I doubt this matters to the main problem but if I put tailwind and tailwind forms in `devDependencies` like you have, I get the following on asset precompilation:

```
SassError: File to import not found or unreadable: tailwindcss/base.

on line 1 of /var/www/src/app/javascript/stylesheets/application.scss

>> @import "tailwindcss/base";
```
🤷🏼‍♂️

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you provide a reproduction repository?
Make sure that the `purge` option lists all the paths where content can be found.
Also make sure that you have `type="text"` on normal inputs for example.

**Comment by DavidVII** [comment]
I've got an elixir/phoenix project with a configuration that's nearly identical to the example @dnsbty shared and it is displaying the same behavior.

Does it seem that PurgeCSS is purging `@tailwindcss/forms` since none of the classes are being used in the HTML?

**Comment by dnsbty** [comment]
Yeah I think part of the problem is that we typically use the `text_input` function from Phoenix.HTML.Form to create the text inputs instead of writing them manually. The project in which I noticed this bug has only a single text input written out in HTML.

I've tried to pare it down to make a simpler replication example without all my proprietary code but had issues replicating.

**Comment by DavidVII** [comment]
Oh interesting, so something like this

```<%= text_input f, :name, class: "tailwind-classes-here" %>```

Would not get treated the same as this:

```<input type="text", name="user["name"]" class="tailwind-classes-here">```

I imagine that's also what @leesmith is seeing this on the Rails end as well.

**Comment by dnsbty** [comment]
Yeah exactly. I don't think the responsibility should lie with tailwind to know how different frameworks create text inputs in order to purge properly though. I think the best solution would be a good way to exclude the normalization from the purge because if I'm adding tailwind forms to my project I will probably always want the normalization piece in place.

**Comment by adamwathan** [comment]
Simplest solution in these situations is probably to just not purge the `base` layer at all:

```js
// tailwind.config.js
module.exports = {
  purge: {
    layers: ['components', 'utilities'],
    content: ['./src/**/*.html'],
  },
  // ...
}
```

https://tailwindcss.com/docs/optimizing-for-production#purging-specific-layers

That will make sure all "reset" rules are kept no matter what. Trivial impact on file size honestly.

Going to close as nothing we can really change within this project to impact the outcome here.

**Comment by leesmith** [comment]
@adamwathan Not purging the base layer totally solved my issue. Thanks for taking your time to respond! 🤘🏼 

I guess since my text inputs had no tailwind classes on them, the styles included in the forms plugin were getting purged?

**Comment by leesmith** [comment]
@DavidVII Regarding your last point...to my understanding, those two snippets you posted are equal as far as purgeable html goes. Where it falls apart is when you use string concatenation to form the tailwind classes.

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by jessedobbelaere** [comment]
Thanks! Adam's workaround of not purging the base layer makes total sense here 👍  

In my case, the tailwindcss-forms styles were getting purged and I didn't realize that I had no actual HTML input fields in my `*.html.twig` files when using [Symfony twig rendering functions](https://symfony.com/doc/current/form/form_customization.html#form-rendering-functions), so PurgeCSS stripped the plugin's styles.
