### ISSUE TITLE
How do I disable radio button focus effect 

### ISSUE THREAD

**Issue by hololink** [tailwindlabs/tailwindcss-forms#47]
Hi, thank you so much for this wonderful plugin. I encounter a problem and stuck there with no luck.
I had already tried this method: https://github.com/tailwindlabs/tailwindcss-custom-forms/issues/37

This is the current code
```
<div class="mt-2">
  <label class="inline-flex items-center">
    <input
      type="radio"
      class="form-radio focus:shadow-none focus:outline-none focus:bg-opacity-0"
      name="privacyType"
      value="private"
    />
    <span class="ml-2">Private</span>
  </label>
  <label class="inline-flex items-center ml-6">
    <input
      type="radio"
      class="form-radio focus:shadow-none focus:outline-none focus:border-transparent"
      name="privacyType"
      value="public"
    />
    <span class="ml-2">Public</span>
  </label>
</div>
```
**Goal: Want to disable this focus ring**
<img width="1280" alt="截圖 2021-02-22 下午11 52 18" src="https://user-images.githubusercontent.com/78023102/108733000-09b7fa00-7569-11eb-9e50-25b36fe84e81.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Internally we use the `ring` utilities, you can apply those to change the style you want.
Example: https://play.tailwindcss.com/9a17lSTOTp

I essentially added this `focus:ring-transparent`, keep in mind that this is very bad for accessibility, so I would recommend to play with the ring utilities until you find something that matches the design and your likings.

**Comment by hololink** [comment]
Sorry for the late reply, I still failed on this problem. I adjust your tailwind css play to indicate the problem.

https://play.tailwindcss.com/7b7oE90unh

You can see a white ring around the radio selection when you first select it, once your mouse click elsewhere, it will disappear. Is there any method to style this white ring?

<img width="1280" alt="截圖 2021-04-22 下午2 40 35" src="https://user-images.githubusercontent.com/78023102/115667732-c0bdcf80-a378-11eb-9671-380714833f9b.png">

<img width="1280" alt="截圖 2021-04-22 下午2 41 28" src="https://user-images.githubusercontent.com/78023102/115667816-d9c68080-a378-11eb-9043-ab5f886b9e70.png">

**Comment by namrog84** [comment]
I am trying to solve this too and was able to get rid of most things

The little 'white dot' in the middle I was able to remove by adding
```
.form-radio:checked
{
  background-image: none;
}

[type='radio']:checked
{
  background-image: none;
}
```

to my index.css (where I import the tailwind stuff).


However I just can't get rid of the white circle, I've gone thru the inspected elements dozens of times 

![image](https://user-images.githubusercontent.com/1614040/205866367-db8fec39-0c43-4f92-9fc4-cc5d4d0008c7.png)

![image](https://user-images.githubusercontent.com/1614040/205866406-e7d4cd3c-e5e6-4be9-8f7a-6703dd5a89b8.png)


Happens when I click and hold, or have recently clicked on something.

What's strange is I don't see it happen

**Comment by fl1k** [comment]
Have same issue.

**Comment by fl1k** [comment]
fixed with focus:ring-offset-0

**Comment by Paintedencode5** [comment]
> I am trying to solve this too and was able to get rid of most things
> 
> The little 'white dot' in the middle I was able to remove by adding
> 
> ```
> .form-radio:checked
> {
>   background-image: none;
> }
> 
> [type='radio']:checked
> {
>   background-image: none;
> }
> ```
> 
> to my index.css (where I import the tailwind stuff).
> 
> However I just can't get rid of the white circle, I've gone thru the inspected elements dozens of times
> 
> ![image](https://user-images.githubusercontent.com/1614040/205866367-db8fec39-0c43-4f92-9fc4-cc5d4d0008c7.png)
> 
> ![image](https://user-images.githubusercontent.com/1614040/205866406-e7d4cd3c-e5e6-4be9-8f7a-6703dd5a89b8.png)
> 
> Happens when I click and hold, or have recently clicked on something.
> 
> What's strange is I don't see it happen





https://stylesheets.space/questions/how-can-you-style-a-radio-button-in-css-while-displaying-a-label-next-to-it
