### ISSUE TITLE
textarea with non-white background looks weird in Firefox

### ISSUE THREAD

**Issue by fs-c** [tailwindlabs/tailwindcss-forms#48]
See [this screenshot](https://i.imgur.com/g2Ry8A5.png) of the `ìndex.html` file with `bg-indigo-200` added to the classes of the `textarea`: The "grabber" of the textarea has a white background, no matter what. This isn't the case normally, but going through the source of this plugin I have no idea what causes the issue. Help would be appreciated.

Edit: For comparison, [here's a screenshot](https://i.imgur.com/eDa7AZa.png) of the doc page for the resize utilities where I added `bg-emerald-200` to one of the textareas. For an illustration of why this is not some obscure use-case, take a look at [this screenshot](https://i.imgur.com/wnMLxpl.png) of an app where I'm currently implementing dark-mode.

**Comment by fs-c** [comment]
Something I should have mentioned in the OP: I am using Firefox 86. Right after making this issue I tested it in a recent Chromium build and it looked fine. I have edited the title accordingly

So I went just brought out my inner caveman and just started toggling off random rules in the devtools: it's the `appearance: none` reset that causes the issue. I'm honestly kind of stumped that _removing_ `appearance: none` could ever make a form element look better by default, but there you have it.

Haven't tested on more than recent Firefox and Chrome version, so I'm not confident enough in this to make a PR.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I created this and looked at it on Firefox 97.0.1 https://play.tailwindcss.com/fhTffLauA8 and it looks like this:
<img width="1816" alt="image" src="https://user-images.githubusercontent.com/1834413/155315038-d073d9e9-0d5c-417f-8f7f-c0384c060c05.png">

I don't think this is a Tailwind issue and more like a browser fluke.
