### ISSUE TITLE
how used with cdn tailwindcss

### ISSUE THREAD

**Issue by superastorh** [tailwindlabs/tailwindcss-forms#49]
I need css file to add in my website

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

It is highly recommended to use a build system once you need plugins and configuration options. More information can be found here: https://tailwindcss.com/docs/installation#using-tailwind-via-cdn

If you really need a CDN link, you can use this link: 

Latest version available:
```html
<link href="https://unpkg.com/@tailwindcss/forms/dist/forms.min.css" rel="stylesheet">
```

Pinned version:
```html
<link href="https://unpkg.com/@tailwindcss/forms@0.2.1/dist/forms.min.css" rel="stylesheet">
```

**Comment by bilogic** [comment]
```
<link href="https://unpkg.com/@tailwindcss/forms/dist/forms.min.css" rel="stylesheet">
```

No longer works for 0.5.8 as there isn't a dist folder
