### ISSUE TITLE
Upgrading from v0.2.0 to v0.3.0 removes all styling

### ISSUE THREAD

**Issue by botre** [tailwindlabs/tailwindcss-forms#60]
### What version of @tailwindcss/forms are you using?

v0.3.0

### What version of Node.js are you using?

12.16

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

NA

Upgrading from v0.2.0 to v0.3.0 removes all input styling.

Is there a migration step somewhere I missed?

Code:

```jsx
<input className={`block w-full placeholder-gray-400 border-gray-300 focus:ring-java-500 focus:border-java-500 rounded px-3 py-2`}
 />
```

Before (0.2):

![before](https://user-images.githubusercontent.com/10811687/112593163-611ae580-8e07-11eb-90dd-f07a6bf94ad9.png)

After (0.3):

![after](https://user-images.githubusercontent.com/10811687/112593178-6841f380-8e07-11eb-9920-9622f8edfdaf.png)

**Comment by Xenonym** [comment]
Seems like the default strategy was changed to `class` in 3bfbd1af0aeef979ce8bc9eb5b4930193d7ab618, possibly by accident? @adamwathan

The docs seem to imply that [`class` is optional](https://github.com/tailwindlabs/tailwindcss-forms#using-classes-instead-of-element-selectors).

In the meantime, you can workaround this by explicitly specifying the `base` strategy:
```js
// tailwind.config.js
plugins: [
 require("@tailwindcss/forms")({
   strategy: 'base',
 }),
],
```

**Comment by jcsoriano** [comment]
Also experiencing this. 

This is my form when `@tailwindcss/forms:^2.1`

<img width="470" alt="image" src="https://user-images.githubusercontent.com/5937317/112611960-630d9480-8e59-11eb-916b-88fa203f2111.png">

And this is my form after upgrading to `^3.0`

<img width="452" alt="image" src="https://user-images.githubusercontent.com/5937317/112612047-728cdd80-8e59-11eb-891d-8719bb1e27f3.png">
