### ISSUE TITLE
Project prefix feature is not working for class strategy

### ISSUE THREAD

**Issue by prgrssm** [tailwindlabs/tailwindcss-forms#64]
### What version of @tailwindcss/forms are you using?

v0.3.1

### What version of Node.js are you using?

v15.12.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

none

After adding prefix to tailwind config it's not applied to "class" strategy generated rules.  Is it a bug?

**Comment by andreasnuesslein** [comment]
hello, are there any news on this?

cheers

**Comment by dextermb** [comment]
I've just ran into this issue as well. Damn

**Comment by andreasnuesslein** [comment]
> I've just ran into this issue as well. Damn

for some reason I fixed it by just changing ".vue" to the beginning of the `content`:
`content: ["./src/**/*.{html,js,vue,ts}"]` -> `content: ["./src/**/*.{vue,html,js,ts}"]`

**Comment by simonc** [comment]
Hi there. Faced the same issue today. Another related aspect is that it's not respecting the `important: true` setting either it seems.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This has been fixed by #91 and will be available in the next release!
