### ISSUE TITLE
Class Strategy still applies all styles by default

### ISSUE THREAD

**Issue by creativiii** [tailwindlabs/tailwindcss-forms#67]
### What version of @tailwindcss/forms are you using?

0.3.2

### What version of Node.js are you using?

14.0.0

### What browser are you using?

12.18.2

### What operating system are you using?

Windows with WSL

### Reproduction repository

none

### Describe your issue

I'm unsure if I'm understanding this right but if I use:

```
  plugins: [
    require('@tailwindcss/forms'),
    {
      strategy: 'class',
    },
  ],
```

Then the styles should not be applied unless I specifically add their classes to my inputs, correct?

This doesn't seem to be happening, all styles are applied to all inputs even if I use the `strategy` option.

**Comment by adamwathan** [comment]
Hey! Your code is incorrect, should be this:

```
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
  ],
```

**Comment by creativiii** [comment]
Wow I'm a dummy, thank you!
