### ISSUE TITLE
[Bug]: Strategy Class Doesn't work

### ISSUE THREAD

**Issue by jasonlimantoro** [tailwindlabs/tailwindcss-forms#68]
### What version of @tailwindcss/forms are you using?

v0.3.2

### What version of Node.js are you using?

v12.13.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

MacOS

### Reproduction repository

N/A

### Describe your issue

After declaring strategy class like so,
```js
require("@tailwindcss/forms", {
	strategy: "class",
}),
```
all inputs are still being reset as if the `{ strategy: "class"} ` wasn't there.

### Expected
Input style should be opt-in only

**Comment by jasonlimantoro** [comment]
Silly mistake:

The config should be like this:
```js
 require("@tailwindcss/forms")({
       strategy: 'class',
 }),
```

and not this:
```js
require("@tailwindcss/forms", {
	strategy: "class",
})
```

**Comment by yob-yob** [comment]
why is mine saying `require(...) is not a function`

**Comment by yob-yob** [comment]
> why is mine saying `require(...) is not a function` ?

Nevermind, I was using a lower version, I just updated to v0.3.3
