### ISSUE TITLE
The styles aren't being loaded from unpkg on the demo site

### ISSUE THREAD

**Issue by mvasin** [tailwindlabs/tailwindcss-forms#73]
The styles are broken on the demo site https://tailwindcss-forms.vercel.app/. Here's a screenshot:

<img width="1536" alt="Screenshot 2021-06-20 at 15 48 11" src="https://user-images.githubusercontent.com/12434833/122676582-f4816e00-d1de-11eb-95d7-74dc67b4470e.png">

**Comment by adamwathan** [comment]
Fixed, thank you!
