### ISSUE TITLE
Does not reset forms

### ISSUE THREAD

**Issue by nimabrownlee** [tailwindlabs/tailwindcss-forms#80]
### What version of @tailwindcss/forms are you using?

v0.3.3

### What version of Node.js are you using?

v16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://gitlab.com/nimabrownlee/tailwindforms-bug

### Describe your issue

I've absolutely no idea why it doesn't work. I have it setup in another project but this one doesn't work at all. I'm not sure if I've missed a step. It doesn't reset the styling of form inputs.

**Comment by adamwathan** [comment]
Hey! You're missing `type="text"` on your input.

From the docs:

> **Note that for text inputs, you must add the type="text" attribute for these styles to take effect.** This is a necessary trade-off to avoid relying on the overly greedy input selector and unintentionally styling elements we don't have solutions for yet, like input[type="range"] for example.

Hope that helps 🍻

**Comment by pavloko** [comment]
I think this should be bolder in the docs:)
