### ISSUE TITLE
input[type="date"] related placeholder missing on Mobile Browser

### ISSUE THREAD

**Issue by zernonia** [tailwindlabs/tailwindcss-forms#85]
### What version of @tailwindcss/forms are you using?

v0.3.4 (maybe)

### What version of Node.js are you using?

-

### What browser are you using?

Chrome (Mobile)

### What operating system are you using?

-

### Reproduction repository

-

### Describe your issue

The placeholder of input[type="date"] and related input is missing on [Tailwind-form website](https://tailwindcss-forms.vercel.app/)

Image showing that it works on PC responsive view, displaying "dd/mm/yyyy"
![date placeholder correct](https://user-images.githubusercontent.com/59365435/135863504-16e609a8-ba51-47e7-a26c-8752ffdcf04f.PNG)

But it is missing in Chrome mobile
![date placeholder missing](https://user-images.githubusercontent.com/59365435/135864055-b447430e-ac89-48e5-8423-8589515c4aa8.jpg)

**Comment by adamwathan** [comment]
Tested on a Pixel 5 and confirmed, Chrome on Android just doesn't show that native placeholder, just how they've decided to do it. Going to close since not in scope for us, thanks though.
