### ISSUE TITLE
Docs: Duplicate copy for NPM and Yarn when installing from docs.

### ISSUE THREAD

**Issue by lennon-mudenda** [tailwindlabs/tailwindcss-forms#87]
### What version of @tailwindcss/forms are you using?

0.3.4

### What version of Node.js are you using?

6.14.15

### What browser are you using?

Brave, Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

https://github.com/lennon-mudenda/tailwindcss-forms

### Describe your issue

Its my first day using tailwind-forms and to make my life easier I decided to copy the install script from the docs using the copy button. However, since some comments and the install command for yarn is under the same button it copied both and it ran the install for NPM and Yarn on my machine which would require cleaning up for someone with both NPM and Yarn on their machine or it could possibly throw an error in the command line. I can resolve the issue because its just docs and its something that requires a rewrite of that section only in the docs.

**Comment by bradlc** [comment]
Hey @lennon-mudenda. That's a good point about the copy button, thanks! We have gone ahead and updated the install commands across all of our plugins (https://github.com/tailwindlabs/tailwindcss-forms/commit/0b1e872ab30a7073fe283c7ea75a63ded7398206, https://github.com/tailwindlabs/tailwindcss-line-clamp/commit/d2320eaa74592bc6156efbd27cfa27918b36a31a, https://github.com/tailwindlabs/tailwindcss-aspect-ratio/commit/936b849dfafc348bf9431650c6b2fb52a0a584a2), so this shouldn't be an issue anymore 👍

**Comment by lennon-mudenda** [comment]
Hey @bradlc thanks for the update.
