### ISSUE TITLE
Tailwindcss-forms is meant to replace tailwindcss-custom-forms when using Tailwindcss v2?

### ISSUE THREAD

**Issue by ptarmic** [tailwindlabs/tailwindcss-forms#9]
Little confused about what the difference is between this and tailwindcss-custom-forms and whether this is the preferred option going forward with tailwindcss v2 or meant to be alternative form fields option.

**Comment by prashantp26** [comment]
> Little confused about what the difference is between this and tailwindcss-custom-forms and whether this is the preferred option going forward with tailwindcss v2 or meant to be alternative form fields option.

Below quote should answer your question.

From docs:
"I tried to solve this a while back with the @tailwindcss/custom-forms plugin, but something about adding a bunch of classes like form-input and form-checkbox just didn't feel quite right so we didn't really promote it and didn't even link to it from the Tailwind documentation. This time though I think we figured it out."

**Comment by grantsayer** [comment]
Just a short question - do you need to user both **npm** and **yarn** for the install ?

**Comment by iksaku** [comment]
@grantsayer No, you can either use `npm` or `yarn`, it doesn't matter which one.
