### ISSUE TITLE
Bg-color changes to blue after an input is made in text

### ISSUE THREAD

**Issue by thekesslereffect** [tailwindlabs/tailwindcss-forms#92]
### What version of @tailwindcss/forms are you using?

0.3.4

### What version of Node.js are you using?

12.22.6

### What browser are you using?

brave

### What operating system are you using?

windows

### Reproduction repository

https://replit.com/@NickRutlinh/Only-Bans#files/nft.html

### Describe your issue

I can change the bg-color of a text input to black. But once there is an input it changes to light blue.

**Comment by thekesslereffect** [comment]
figured out the issue. It was because of autocomplete. I just added autocomplete="off" and things worked correctly

**Comment by adamwathan** [comment]
Glad to hear you resolved it!
