### ISSUE TITLE
input type="date" is more height for other type, and calendar is too small on safari browser

### ISSUE THREAD

**Issue by little3201** [tailwindlabs/tailwindcss-forms#95]
### What version of @tailwindcss/forms are you using?

0.3.4

### What version of Node.js are you using?

V16.13.0

### What browser are you using?

safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/little3201/leafage-ms

### Describe your issue

input type="date" is more heighter than other type, and calendar is too small on safari browser, but edge is ok.

**the type of date:**
<img width="796" alt="Screen Shot 2021-12-04 at 10 51 33" src="https://user-images.githubusercontent.com/34156125/144694331-867b13a9-c466-41dd-9f20-9930cb9a347c.png">

**the calendar:**
<img width="444" alt="Screen Shot 2021-12-04 at 10 53 36" src="https://user-images.githubusercontent.com/34156125/144694377-8759afe8-ddde-4c0f-8217-b28476ecabe3.png">

**Comment by little3201** [comment]
When will it be released?

**Comment by thecrypticace** [comment]
Going to tag a release today!
