### ISSUE TITLE
No longer works in the last version of tailwind. 

### ISSUE THREAD

**Issue by silicahd** [tailwindlabs/tailwindcss-forms#97]
### What version of @tailwindcss/forms are you using?

tailwindcss v3.0.12

### What version of Node.js are you using?

v14.18.1

### What browser are you using?

NA

### What operating system are you using?

cent os 8

### Reproduction repository

See issue

### Describe your issue

I thought this was my installation but after a few tires maybe it is time to throw in towel. 

I installed the last version of Tailwind CSS and everything works great with the last version JIT. 

However I noticed that I used a few forms so I tried to install the forms. 

First installed using "npm install @tailwindcss/forms"
Than added 
``` 
    plugins: [
        require('@tailwindcss/forms'),
  ], 
```

When I try to run "npm run dev" i get this error. 

If i remove the plugin it works fine. I also tried other plugins with no issues. 
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property '500' of undefined
```

**Comment by silicahd** [comment]
Found the issue 

run 

```
npm install laravel-mix@latest @tailwindcss/forms@latest
```

**Comment by reinink** [comment]
Yup, exactly, you need update to the latest version of the forms plugin for Tailwind CSS v3.0. This is covered in our [upgrade guide](https://tailwindcss.com/docs/upgrade-guide):

> All of our first-party plugins have been updated for compatibility with v3.0.
> 
> If you’re using any of our plugins, make sure to update them all to the latest version at the same time to avoid version constraint errors.

Glad you got it figured out 👍

**Comment by ralphjsmit** [comment]
Thanks @silicahd! Had exactly the same problem.👍
