### ISSUE TITLE
Form fields are much larger than on https://tailwindui.com/components/application-ui/forms/input-groups.

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/tailwindcss-forms#98]
### What version of @tailwindcss/forms are you using?

v0.4.0

### What version of Node.js are you using?

v17.1.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://tailwindcss-forms.vercel.app

### Describe your issue

I purchased tailwindui.com and love the design.

I've copied and pasted the code from [tailwindui.com/input-groups](https://tailwindui.com/components/application-ui/forms/input-groups), and installed tailwindcss-forms.

I found form fields are significantly bigger than the examples shown when using tailwindcss-form. You can see this when visiting https://tailwindcss-forms.vercel.app.

**Comment by natemate90** [comment]
According to the changelog, 0.4.0 is only compatible with Tailwind CSS v3.0. What version of Tailwind CSS are you using?

https://github.com/tailwindlabs/tailwindcss-forms/releases

**Comment by ACPK** [comment]
@natemate90 It is the sample app provided in the repo (https://tailwindcss-forms.vercel.app).
